name: guru
version: "0.1.0"
authors: Daniel Hammeley <daniel@hammeley.info>
about: Predict Football Matches
args:
    - error:
        help: The maximum network error
        short: e
        long: error
        required: true
        takes_value: true
    - data:
        help: File name of the training data
        short: d
        long: data
        required: false
        takes_value: true
    - load-network:
        help: Loads a previously trained network
        short: l
        long: load-network
        required: false
        takes_value: false
    - save-network:
        help: Saves a trained network to file
        short: s
        long: save-network
        required: false
        takes_value: false
    - split-data:
        help: Splits the data set into a training and a test set according to this factor
        long: split-data
        required: false
        takes_value: true
    - no-train:
        help: Does not train the network prior testing and prediction.\nCan be used for debug or if a trained network is loaded from file.
        long: no-train
        required: false
        takes_value: false